### ISSUE TITLE
Add support for search plugin

### ISSUE THREAD

**Issue by carylee** [ritesh83/ember-cli-jstree#53]
We're using `ember-cli-jstree` and needed support for the search plugin. I got this working for us over at https://github.com/usermindinc/ember-cli-jstree (currently in internal PR at https://github.com/usermindinc/ember-cli-jstree/pull/1), but it conflicts with existing functionality for `selectNodes` when used with a non-id property, which leverages explicit search callback. We don't use this functionality, so I didn't need to maintain it for our purposes.

If you have any thoughts on how we could continue to support `selectNodes` as is and add support for the search plugin, I'd be happy to help implement it. It could be potentially done by an exclusive feature flag (i.e. you get selectNodes on non-id properties or regular search, but not both).

**Comment by cristinawithout** [comment]
The data in jstree is available via treeObject.jstree(true)._model.data.original. That seems to be intended to be private (hence _), but we could still get access to it in order to find the node ID.

Alternately, we could make a jstree plugin that just finds a node by a given original property, which doesn't need to be as complex as the search plugin. Then the component would always enable that plugin via the config in order to always support select by non-id property.

**Comment by cristinawithout** [comment]
@carylee PR has been merged. Please confirm it addresses your issue.

**Comment by carylee** [comment]
Looks great, thanks a lot! I'll merge these changes into my fork and open a PR to support the search plugin.

**Comment by carylee** [comment]
I opened https://github.com/ritesh83/ember-cli-jstree/pull/56 to support the search plugin.

**Comment by ritesh83** [comment]
Merged pull request
